export const data = [
    {
        no:1,
        nama:'John Doe',
        email:'johndoe@gmail.com',
        notelp:628123456789,
        status:true,
    },
    {
        no:2,
        nama:'John Doe',
        email:'johndoe@gmail.com',
        notelp:628123456789,
        status:false,
    },
    {
        no:3,
        nama:'John Doe',
        email:'johndoe@gmail.com',
        notelp:628123456789,
        status:true,
    },
    {
        no:4,
        nama:'John Doe',
        email:'johndoe@gmail.com',
        notelp:628123456789,
        status:false,
    },
    {
        no:5,
        nama:'John Doe',
        email:'johndoe@gmail.com',
        notelp:628123456789,
        status:true,
    },
    {
        no:6,
        nama:'John Doe',
        email:'johndoe@gmail.com',
        notelp:628123456789,
        status:false,
    },
    {
        no:7,
        nama:'John Doe',
        email:'johndoe@gmail.com',
        notelp:628123456789,
        status:true,
    },
    {
        no:8,
        nama:'John Doe',
        email:'johndoe@gmail.com',
        notelp:628123456789,
        status:false,
    },
    {
        no:9,
        nama:'John Doe',
        email:'johndoe@gmail.com',
        notelp:628123456789,
        status:true,
    },
    {
        no:10,
        nama:'John Doe',
        email:'johndoe@gmail.com',
        notelp:628123456789,
        status:false,
    },
]