export const data = [
  {
    no: 1,
    pengirim: "John Doe",
    keterangan: "Surat Masuk",
    tanggal: "10-10-2022",
    status: "Belum Dibaca",
    draft: "-",
  },
  {
    no: 2,
    pengirim: "John Doe",
    keterangan: "Surat Masuk",
    tanggal: "10-10-2022",
    status: "Belum Dibaca",
    draft: "-",
  },
  {
    no: 3,
    pengirim: "John Doe",
    keterangan: "Surat Masuk",
    tanggal: "10-10-2022",
    status: "Belum Dibaca",
    draft: "-",
  },
  {
    no: 4,
    pengirim: "John Doe",
    keterangan: "Surat Masuk",
    tanggal: "10-10-2022",
    status: "Belum Dibaca",
    draft: "-",
  },
  {
    no: 5,
    pengirim: "John Doe",
    keterangan: "Surat Masuk",
    tanggal: "10-10-2022",
    status: "Belum Dibaca",
    draft: "-",
  },
  {
    no: 6,
    pengirim: "John Doe",
    keterangan: "Surat Masuk",
    tanggal: "10-10-2022",
    status: "Belum Dibaca",
    draft: "-",
  },
  {
    no: 7,
    pengirim: "John Doe",
    keterangan: "Surat Masuk",
    tanggal: "10-10-2022",
    status: "Belum Dibaca",
    draft: "-",
  },
  {
    no: 8,
    pengirim: "John Doe",
    keterangan: "Surat Masuk",
    tanggal: "10-10-2022",
    status: "Belum Dibaca",
    draft: "-",
  },
  {
    no: 9,
    pengirim: "John Doe",
    keterangan: "Surat Masuk",
    tanggal: "10-10-2022",
    status: "Belum Dibaca",
    draft: "-",
  },
  {
    no: 10,
    pengirim: "John Doe",
    keterangan: "Surat Masuk",
    tanggal: "10-10-2022",
    status: "Belum Dibaca",
    draft: "-",
  },
];
