export const data = [
    {
        no: 1,
        pengirim: "John Doe",
        keterangan: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Saepe corrupti magni possimus esse beatae deserunt dolorem modi veniam nam accusantium.',
        tanggal: "10-10-2022",
        status: true,
    },
    {
        no: 2,
        pengirim: "John Doe",
        keterangan: "Balasan surat cinta untuk starla",
        tanggal: "10-10-2022",
        status: false,
    },
    {
        no: 3,
        pengirim: "John Doe",
        keterangan: "Balasan surat cinta untuk starla",
        tanggal: "10-10-2022",
        status: false,
    },
    {
        no: 4,
        pengirim: "John Doe",
        keterangan: "Balasan surat cinta untuk starla",
        tanggal: "10-10-2022",
        status: true,
    },
    {
        no: 5,
        pengirim: "John Doe",
        keterangan: "Balasan surat cinta untuk starla",
        tanggal: "10-10-2022",
        status: true,
    },
    {
        no: 6,
        pengirim: "John Doe",
        keterangan: "Balasan surat cinta untuk starla",
        tanggal: "10-10-2022",
        status: true,
    },
    {
        no: 7,
        pengirim: "John Doe",
        keterangan: "Balasan surat cinta untuk starla",
        tanggal: "10-10-2022",
        status: false,
    },
    {
        no: 8,
        pengirim: "John Doe",
        keterangan: "Balasan surat cinta untuk starla",
        tanggal: "10-10-2022",
        status: true,
    },
    {
        no: 9,
        pengirim: "John Doe",
        keterangan: "Balasan surat cinta untuk starla",
        tanggal: "10-10-2022",
        status: false,
    },
    {
        no: 10,
        pengirim: "John Doe",
        keterangan: "Balasan surat cinta untuk starla",
        tanggal: "10-10-2022",
        status: false,
    },
]